### ISSUE TITLE
Changes to the Settings Screen

### ISSUE THREAD

**Issue by radwahm** [StatCan/StatcanPublicationUAT#480] opened 2022-10-05 14:35 UTC
https://confluenceb.statcan.ca/display/SPMA/Feature+7.1+-+Changes+to+the+Settings+page

**Comment by radwahm** [comment] 2022-11-01 15:20
Signed off on October 26th, 2022.

**Comment by weglmar** [comment] 2023-02-03 16:53
Closing as this is a duplicate of #475

**Closed by weglmar** 2023-02-03 16:53 UTC
Labels: Enhancement, XLARGE, Ready For Development
