### ISSUE TITLE
Fix the UX for Tab bar on iOS

### ISSUE THREAD

**Issue by Rajat-Sen** [StatCan/StatcanPublicationUAT#337] opened 2022-03-24 13:14 UTC
The icons on the tab bar needs to be moved up as there needs to be room between home indicator and the icons itself. 

Attaching image for reference.

**Comment by Rajat-Sen** [comment] 2022-03-24 13:15
![image](https://user-images.githubusercontent.com/38566088/159924038-6b024994-198a-4571-a577-0536d51d8088.png)

**Comment by Rajat-Sen** [comment] 2022-03-24 13:16
This is normal tab bar on other apps.

![image](https://user-images.githubusercontent.com/38566088/159924286-45fef130-0f01-4f15-96e0-70ab86a60104.png)

**Comment by ForumG-SC** [comment] 2022-03-24 13:38
Related to #334

**Comment by AJBouzidi** [comment] 2022-03-25 16:53
@ForumG-SC this is will be part of the 29th deployment. Improvement needed for the spacing.

**Comment by Jiandong-Guo** [comment] 2022-03-29 17:06
It doesn't exist in new component.  we can say it fixed

**Comment by Jiandong-Guo** [comment] 2022-03-29 17:07
Please test it in next release

**Comment by Rajat-Sen** [comment] 2022-03-30 18:36
Was this tested properly on simulator before releasing?

Please see the attached screenshot.

**Comment by Rajat-Sen** [comment] 2022-03-30 18:37
![image](https://user-images.githubusercontent.com/38566088/160907259-5853f5ac-d838-44bf-a783-33f4844e8b00.png)

**Comment by Jiandong-Guo** [comment] 2022-03-30 20:54
Yes, The screen shot was what I tested on simulator.

**Comment by Rajat-Sen** [comment] 2022-03-31 11:02
This is not how it was supposed to look like. I have attached screenshot from other app. Please make changes accordingly.

**Comment by Rajat-Sen** [comment] 2022-03-31 11:04
![image](https://user-images.githubusercontent.com/38566088/161041081-753f48a0-4591-4ee5-8e67-4ab0102e059a.png)

**Comment by Rajat-Sen** [comment] 2022-03-31 11:28
Also, please test on iPad as well and attach screenshot for reference. Thanks!

**Comment by Jiandong-Guo** [comment] 2022-03-31 13:31
@Rajat-Sen What you want to change exactly ?

**Comment by Pharste** [comment] 2022-03-31 13:54
Tested on iPad Pro: 
![Bottom menu bar ipad dark](https://user-images.githubusercontent.com/89025880/161071879-d49f27f7-3ba8-4997-b7a6-0841e55fe22c.png)
![Bottom menu bar ipad](https://user-images.githubusercontent.com/89025880/161071886-797f15b3-43d7-41ef-9696-403ca6552079.png)

**Comment by Jiandong-Guo** [comment] 2022-03-31 15:43
This is for iphone 
![iphone 8](https://user-images.githubusercontent.com/58485300/161095613-5d661068-1bb2-40b0-a456-c893ea3a7dde.png)
8

**Comment by Jiandong-Guo** [comment] 2022-03-31 15:44
That is for iphone 8

**Comment by Rajat-Sen** [comment] 2022-03-31 15:48
@Jiandong-Guo It's still not fixed well.

In light mode, there is colour difference between home indicator and tab bar.
In dark mode, the home indicator should be in white colour.

**Comment by Jiandong-Guo** [comment] 2022-03-31 15:53
If the problem is to cover the bottom border, it seems only for iphone 12 pro max, for iphone 8, it is a physical border, for the iphone 12, it is a virtual border, we can extend the our screen to cover the bottom, but in dark mode, the virtual button is almost invisible, the virtual button is from system, don't know how to style it yet. that needs time to research

**Comment by Jiandong-Guo** [comment] 2022-03-31 15:54
I didn't fix it yet, just start to test the feasibility

**Comment by Rajat-Sen** [comment] 2022-03-31 17:25
Also, the Tab Bar doesn't change colour in dark mode. Please see the attached screenshot.

**Comment by Jiandong-Guo** [comment] 2022-03-31 19:25
After searching awhile and found:
The home indicator was introduced in after iphone X, and will be phase out in the future.
The home indicator’s color is determined by the system and cannot be modified directly.
The home indicator’s color is determined by the content underneath, and it is not always a solid color. you can change the underneath color to let system to change the color for you, but the color changes among black, gray, dark gray and very dark gray
The home indicator on the simulator is not an accurate representation of the home indicator on a real device.
The home indicator animates to its new color(s) when the content underneath changes.
The home indicator is either in a “light” or “dark” state. 
You can search "home indicator color for iphone x", you will find that seems "half of world" want to change the color.
The result seems no way to change it.

**Comment by Jiandong-Guo** [comment] 2022-04-04 13:57
the answer from apple:    https://developer.apple.com/forums/thread/86906 

so we have to decide which way to implement: 1)leave a bottom border, 2)ignore the dark home indicator

**Comment by AJBouzidi** [comment] 2022-04-07 18:06
@Rajat-Sen this ticket contain basically 3 issues. 
1-Space with and size icons and the spacing current ticket (https://github.com/StatCan/StatcanPublicationUAT/issues/337)
2-Home indicator (https://github.com/StatCan/StatcanPublicationUAT/issues/358)
3-Darkmode for the tab navigator (https://github.com/StatCan/StatcanPublicationUAT/issues/359)

For now we create a ticket for each issue. 
As best practice please do not include many issue in the same ticket.

**Comment by payeisa** [comment] 2022-04-19 14:36
@AJBouzidi I'm not sure why this ticket was assigned to me (it was submitted by Rajat). Thanks, Isabelle

**Comment by ForumG-SC** [comment] 2022-04-21 13:36
@Jiandong-Guo Hi Jiandong, seems like the tab bar is not fixed for bigger devices like ipad.

**Comment by Jiandong-Guo** [comment] 2022-04-21 17:33
![image](https://user-images.githubusercontent.com/58485300/164517935-c06895bc-bd41-4cf0-a8f3-533b93b4a92f.png)
![image](https://user-images.githubusercontent.com/58485300/164517977-828b1768-4cf1-489e-948c-996a1d8ca652.png)

**Comment by ForumG-SC** [comment] 2022-04-21 17:39
> ![image](https://user-images.githubusercontent.com/58485300/164517935-c06895bc-bd41-4cf0-a8f3-533b93b4a92f.png) ![image](https://user-images.githubusercontent.com/58485300/164517977-828b1768-4cf1-489e-948c-996a1d8ca652.png)

@Jiandong-Guo Hi Jiandong, thanks for sharing the screenshots. I believe the tab bar should look identical to mobile devices where the text should be under the icons not beside.

**Comment by Jiandong-Guo** [comment] 2022-04-22 20:25
![image](https://user-images.githubusercontent.com/58485300/164788796-a8837af9-8bfa-4a6a-afd7-8793cc0ef1fe.png)

**Comment by Pharste** [comment] 2022-05-02 19:15
Hi, I've validated on iPad, and although the text is under the icons as it should be, the spacing looks off from the prototype. It should have more space between the icon and top of the menu bar, and more spacing between the text and icon. I believe the icons are a little bigger in the prototype as well.

**Comment by AJBouzidi** [comment] 2022-05-05 20:15
Reason: Fixed
Description: UX improvement has been done for all devices
Release App: Prod, Alpha
Release version: 1.0.6

**Closed by AJBouzidi** 2022-05-05 20:15 UTC
Labels: enhancement
