### ISSUE TITLE
Publishing failure: ORPS

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#300] opened 2022-02-02 13:49 UTC
This morning, the booking tool failed to publish the article Accommodation Services, 2020. 

I tried to publish at 8:35 am, and it didn't give me any error message when I hit save.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/89025880/152166118-2a1bad41-63a0-42e4-a895-c94499f9dd9e.png)

**Comment by goodyke** [comment] 2022-02-02 16:16
However, this issue could be related to the bug reported in ticket #299.  We should keep both of these GitHub tickets open so we can document the findings clearly.

**Comment by goodyke** [comment] 2022-02-03 14:09
The cause of the failed booking was discovered.  The Booking Tool was not verifying the article entered by the user so it was possible to create an invalid booking.  If you look at the image submitted in this ticket then you can see that the value for the **StatCan Plus article** was _Accommodation Services, 2020_.  When a booking is created with a valid article name then the value for StatCan Plus article is an article id (it should have been _301_ in this case).  I am marking this issue as DONE.  The Drupal team will be adding this verification to the Booking Tool and we will let the clients know when this is ready to be tested in ALPHA.  Thanks!

**Comment by goodyke** [comment] 2022-02-03 14:10
Actually I can not update this to DONE as we did not put it in a Sprint.
@Pharste - please close this ticket if satisfied with the outcome.

**Comment by Pharste** [comment] 2022-02-03 14:13
Closed, thank you @goodyke

**Closed** 2022-02-03 14:13 UTC
Labels: Waiting for the backend
