### ISSUE TITLE
Settings: Share this app functionality

### ISSUE THREAD

**Issue by payeisa** [StatCan/StatcanPublicationUAT#212] opened 2022-01-12 02:09 UTC
Should be implemented according to:
User story 4a: Share the StatCan app
User story 4b: Share the StatCan app via email 
User story 4c: Share the StatCan app via a message or on social media

https://confluence.statcan.ca/display/SPMA/Feature+5.3+Support+and+feedback

**Comment by Rajat-Sen** [comment] 2022-01-12 11:53
@payeisa, as of right now this functionality is working as per device OS. Would it be okay if we enhance this after MVP?

**Comment by payeisa** [comment] 2022-01-12 12:04
@Rajat-Sen Sorry, I should have specified, it works, so functionality is ok. But the content is not ok (i.e. the subject, the body of the email etc.)

**Comment by Rajat-Sen** [comment] 2022-01-12 12:16
Thanks for the update! We will try to fix this before releasing the MVP. If not, it will be included in the very first update after releasing the MVP. 
PS: I understand it's an important feature for you especially, in the beginning phase of the app.

**Comment by payeisa** [comment] 2022-01-12 12:48
@Rajat-Sen yes, having the ability to share the app would in fact be a very important feature to have for MVP. Let's discuss Thursday as this was always part of initial requirements.

**Comment by Rajat-Sen** [comment] 2022-01-14 15:19
We will need this functionality working for the MVP. Thanks!

**Comment by Jiandong-Guo** [comment] 2022-01-18 14:20
![image](https://user-images.githubusercontent.com/58485300/149954675-2834a09b-ff7c-4ea6-90e0-feca2845a34a.png)

**Comment by Rajat-Sen** [comment] 2022-01-18 15:30
The name of the app should be changed to "StatsCAN"
There should be proper spacing "If not, you should download it."
Also, please add the link for the iOS store.

Thanks!

**Comment by Jiandong-Guo** [comment] 2022-01-18 17:01
![image](https://user-images.githubusercontent.com/58485300/149983606-e41ec780-911a-4117-b579-86283ecf4bb1.png)

Please test in next release

**Comment by Jiandong-Guo** [comment] 2022-01-18 17:07
![image](https://user-images.githubusercontent.com/58485300/149984553-4b34ea72-77d5-45a6-af6b-67326eabacc4.png)

**Comment by Rajat-Sen** [comment] 2022-01-18 19:04
Hi Jiandong, please change the name of the app in subject as well. (For both, English and French)
Also, there needs to be space after the comma. "If not, you".

Please attach the updated screenshot.

Thanks!

**Comment by Rajat-Sen** [comment] 2022-01-18 19:06
@Jiandong-Guo, Please see the last comment.

**Comment by payeisa** [comment] 2022-01-18 19:40
The subject of the email should be: Do you have the StatsCAN app? / Avez-vous l’appli StatsCAN? 
The body of the email should be: If not, you should download it. / Sinon, vous devriez la télécharger.
The message should also include the app's icon.
See User story 4b: https://confluence.statcan.ca/pages/editpage.action?pageId=904555691

**Comment by Jiandong-Guo** [comment] 2022-01-19 18:09
The icon is not feasible, others are ready to test in next release

**Comment by payeisa** [comment] 2022-01-24 00:38
If sharing by email:
In the subject, in French, please remove the space between "StatsCAN" and "?". (appli StatsCAN?)
In the subject, in English, the text should not break (should be continuous, just like it is in French)
In the body, in English, please add abspace between "not" and "you". (If not, you should download it."
In the body, in French, please replace "le" with "la". (Sinon, vous devriez la télécharger.")

If sharing on Messenger or Snapchat
The subject is not included (but it should)
The app icon is missing for Apple (icon is showing for Google)

**Comment by Pharste** [comment] 2022-01-26 15:32
The "Do you have the StatsCAN app" line is still missing when sharing the app via messenger, text, whatsapp, etc.:
![Whats app share this app](https://user-images.githubusercontent.com/89025880/151193791-2c58b8dd-fb54-4d17-bd84-17c0ff58afe2.jpg)
![Share via text](https://user-images.githubusercontent.com/89025880/151193795-01a01f8b-9ab5-45d9-80dd-f94efada812a.jpg)
![Share this app 1](https://user-images.githubusercontent.com/89025880/151193799-184adea1-0274-4cec-986f-46153b12730c.jpg)

**Comment by payeisa** [comment] 2022-01-26 15:35
Email is ok, however text is missing when sharing on social media (Messenger/Snapchat) or by text.
The text should read:  
FR: Avez-vous l'appli StatsCAN? Sinon, vous devriez la télécharger. / Do you have the StatsCAN app? If not, you should download it.
EN: Do you have the StatsCAN app? If not, you should download it. / Avez-vous l'appli StatsCAN? Sinon, vous devriez la télécharger. 

![image](https://user-images.githubusercontent.com/89025704/151192609-073dd9f7-2cc1-4d53-86e5-214bc618529d.png)

**Comment by Pharste** [comment] 2022-01-26 15:45
When sharing on LinkedIn, only the Google Play link is displayed -- 
![LinkedIn 2](https://user-images.githubusercontent.com/89025880/151196456-e312f983-00a8-4b3d-8d68-9c28e6a283ca.jpg)
<img width="414" alt="LinkedIn" src="https://user-images.githubusercontent.com/89025880/151196459-53e4d4ae-f5b0-425e-a4c2-bcdc47fdcef2.png">

(Shared in private message with Martyna)

**Comment by Rajat-Sen** [comment] 2022-01-26 15:48
Please create new tickets for all three issues as the initial issue is fixed.

**Comment by Pharste** [comment] 2022-01-26 16:05
Submitted tickets 271 and 272

**Comment by ForumG-SC** [comment] 2022-03-07 19:13
@AJBouzidi Seems to be duplicate of #271

**Comment by AJBouzidi** [comment] 2022-03-18 19:10
Duplicate of 271 and 272

**Closed by AJBouzidi** 2022-03-18 19:10 UTC
Labels: bug, Major, Mobility
