### ISSUE TITLE
Search Results displaying incorrectly (StatsCAN v1.0.4)

### ISSUE THREAD

**Issue by weglmar** [StatCan/StatcanPublicationUAT#347] opened 2022-03-31 18:47 UTC
The Search Results on the Search page are displaying incorrectly (every second image is not displaying to the right, but underneath, and the date is duplicated). 
App: StatsCAN (v1.0.4) 

iPhone X, iOS 15.3.1. 

![IMG-7449](https://user-images.githubusercontent.com/98898969/161126949-cced787c-6333-41d7-af6d-e27316bf7830.PNG)
![IMG-7450](https://user-images.githubusercontent.com/98898969/161126964-af6bb30d-8352-4620-8c5e-1d5096f7e4d6.PNG)
)

**Comment by AJBouzidi** [comment] 2022-05-09 21:11
duplicate of #348

**Closed by AJBouzidi** 2022-05-09 21:11 UTC
