### ISSUE TITLE
Delay in loading ORPS content to English Publications screen

### ISSUE THREAD

**Issue by Pharste** [StatCan/StatcanPublicationUAT#299] opened 2022-02-02 13:46 UTC
On February 2, two new publications were booked (around 8:35) and there was a 3-4 minute delay in English. French loaded right away, and the English notifications came in right away.

The two articles were Building permits, December 2021 and Accommodation services, 2020.

**Comment by goodyke** [comment] 2022-02-02 16:21
If this issue is not related or caused by the concern in #300 then we will need to set up a verification test to execute when the next article is published through ORPS (with the tag to go to the mobile app).
@Pharste does PLUS have any additional articles to be published this afternoon? If so then we can test when it appears in the mobile app (on both the EN and FR publication screen) to determine if this concern might be replicated then.  Please let us know the publishing time of the next articles we could test with.  Thanks!

**Comment by goodyke** [comment] 2022-02-02 16:37
An article is booked to be published to the PLUS website and mobile app at 2pm today (February 2nd).  As soon as the article appears on the PLUS website the clients will verify what is shown in the mobile app on the publications screen using the display language of EN and FR.  At the same time... I will verify what articles are returned when using both the EN and FR parameters in the api call that gets the data to the mobile app.

**Comment by goodyke** [comment] 2022-02-03 14:23
- **February 2nd** a test was conducted to ensure the article published at 2pm was returned in the api calls and appeared in the mobile app (EN and FR).  Test PASSED
- **February 3rd** another test was conducted after 8:30am to ensure the four articles created for today's _Daily_ releases were showing up after their publishing time.  Those four articles appeared in the api calls and the mobile app (EN and FR) once it was published.  Test PASSED

Assigning this ticket back to @Pharste.  The clients may ask for a feature to be added in a future version (that allows the user to force the app to refresh the Publications screen) but this request will be done through the regular process (not with this ticket).

**Closed** 2022-02-07 18:32 UTC
